// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdonggwuojxmgzninakz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkb25nZ3d1b2p4bWd6bmluYWt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDc1ODgsImV4cCI6MjA3MDIyMzU4OH0.VWE4CgierjKH4pfwjunHqeRMK5mSFkIlD4ND52WECws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});